-- ============================================================
-- SPARTACUS — Visitor analytics (first-party, self-owned)
-- Run this ONCE in Supabase → SQL Editor → New query → Run.
-- Safe to re-run: everything is idempotent.
--
-- What it does:
--   • page_views      — one row per page view (written by track.js)
--   • page_engagement — one row per view when the visitor leaves,
--                       carrying time-on-page and scroll depth
--   • Row Level Security: the public anon key may INSERT only. It can
--     never read your traffic data — same rule as the leads table.
--   • Reporting views you read from the Supabase dashboard:
--       analytics_daily        — visits/visitors per day
--       analytics_top_pages    — best performing articles
--       analytics_referrers    — where traffic comes from
--       analytics_sources      — UTM campaign performance
--       analytics_lead_sources — WHICH BLOG POST PRODUCED EACH LEAD
--
-- No IP addresses, names or emails are stored here. visitor_id is a
-- random ID the browser generates for itself — not a person.
-- ============================================================

-- 1. PAGE VIEWS -------------------------------------------------------------
create table if not exists public.page_views (
  -- id is generated by the BROWSER so the engagement row can reference it
  -- without needing read access to this table.
  id             uuid primary key,
  created_at     timestamptz not null default now(),

  -- who (anonymous, first-party only)
  visitor_id     text not null,
  session_id     text not null,
  is_new_visitor boolean default false,

  -- what
  site           text,          -- 'blog' | 'main'
  path           text not null,
  page_type      text,          -- 'blog_post' | 'blog_listing' | 'page'
  slug           text,          -- blog post slug, when page_type = 'blog_post'
  title          text,

  -- where from
  referrer       text,
  referrer_host  text,
  utm_source     text,
  utm_medium     text,
  utm_campaign   text,
  utm_term       text,
  utm_content    text,

  -- device context (no fingerprinting, just useful buckets)
  device         text,          -- 'mobile' | 'tablet' | 'desktop'
  browser        text,
  os             text,
  screen_w       integer,
  viewport_w     integer,
  language       text,
  timezone       text
);

create index if not exists page_views_created_at_idx on public.page_views (created_at desc);
create index if not exists page_views_slug_idx       on public.page_views (slug);
create index if not exists page_views_visitor_idx    on public.page_views (visitor_id);
create index if not exists page_views_session_idx    on public.page_views (session_id);
create index if not exists page_views_site_idx       on public.page_views (site);
create index if not exists page_views_referrer_idx   on public.page_views (referrer_host);

-- 2. ENGAGEMENT (written when the visitor leaves the page) -------------------
create table if not exists public.page_engagement (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  view_id      uuid not null,        -- matches page_views.id
  duration_ms  integer,              -- time actually on the page
  max_scroll   integer,              -- furthest scroll reached, 0–100 (%)
  clicks       integer default 0,    -- CTA / WhatsApp / link clicks
  reached_cta  boolean default false -- did they scroll to the lead form?
);

create index if not exists page_engagement_view_idx    on public.page_engagement (view_id);
create index if not exists page_engagement_created_idx on public.page_engagement (created_at desc);

-- 3. ROW LEVEL SECURITY ------------------------------------------------------
-- Locked by default; the only thing the website's public key may do is INSERT.
alter table public.page_views      enable row level security;
alter table public.page_engagement enable row level security;

drop policy if exists "anon can record page views" on public.page_views;
create policy "anon can record page views"
  on public.page_views for insert to anon with check (true);

drop policy if exists "anon can record engagement" on public.page_engagement;
create policy "anon can record engagement"
  on public.page_engagement for insert to anon with check (true);

-- You (signed in) can read everything.
drop policy if exists "authenticated can read page views" on public.page_views;
create policy "authenticated can read page views"
  on public.page_views for select to authenticated using (true);

drop policy if exists "authenticated can read engagement" on public.page_engagement;
create policy "authenticated can read engagement"
  on public.page_engagement for select to authenticated using (true);

-- 4. REPORTING VIEWS ---------------------------------------------------------
-- security_invoker = the view respects the RLS of whoever queries it, so anon
-- cannot read your traffic through a view either.

-- Daily traffic ---------------------------------------------------------------
create or replace view public.analytics_daily
with (security_invoker = true) as
select
  date_trunc('day', created_at)::date       as day,
  coalesce(site, 'main')                    as site,
  count(*)                                  as page_views,
  count(distinct visitor_id)                as visitors,
  count(distinct session_id)                as sessions,
  count(*) filter (where is_new_visitor)    as new_visitors
from public.page_views
group by 1, 2
order by 1 desc, 2;

-- Best performing pages (last 30 days) ---------------------------------------
create or replace view public.analytics_top_pages
with (security_invoker = true) as
select
  v.path,
  v.slug,
  coalesce(max(v.title), v.path)                    as title,
  count(*)                                          as page_views,
  count(distinct v.visitor_id)                      as visitors,
  round(avg(e.duration_ms) / 1000.0, 1)             as avg_seconds,
  round(avg(e.max_scroll), 0)                       as avg_scroll_pct,
  count(*) filter (where e.reached_cta)             as reached_lead_form
from public.page_views v
left join public.page_engagement e on e.view_id = v.id
where v.created_at > now() - interval '30 days'
group by v.path, v.slug
order by page_views desc;

-- Where traffic comes from ---------------------------------------------------
create or replace view public.analytics_referrers
with (security_invoker = true) as
select
  coalesce(nullif(referrer_host, ''), '(direct)') as referrer_host,
  count(*)                                        as page_views,
  count(distinct visitor_id)                      as visitors,
  min(created_at)                                 as first_seen,
  max(created_at)                                 as last_seen
from public.page_views
group by 1
order by page_views desc;

-- Campaign / UTM performance --------------------------------------------------
create or replace view public.analytics_sources
with (security_invoker = true) as
select
  coalesce(nullif(utm_source, ''),   '(none)') as utm_source,
  coalesce(nullif(utm_medium, ''),   '(none)') as utm_medium,
  coalesce(nullif(utm_campaign, ''), '(none)') as utm_campaign,
  count(*)                                     as page_views,
  count(distinct visitor_id)                   as visitors,
  count(distinct session_id)                   as sessions
from public.page_views
group by 1, 2, 3
order by page_views desc;

-- WHICH ARTICLE PRODUCED THE LEAD --------------------------------------------
-- Reads the attribution that blog-lead.js writes into leads.utm.
create or replace view public.analytics_lead_sources
with (security_invoker = true) as
select
  l.created_at,
  l.full_name,
  l.phone,
  l.program_interest,
  l.status,
  l.utm ->> 'page'         as landed_on,
  l.utm ->> 'slug'         as blog_slug,
  l.utm ->> 'title'        as blog_title,
  l.utm ->> 'referrer'     as referrer,
  l.utm ->> 'utm_source'   as utm_source,
  l.utm ->> 'utm_campaign' as utm_campaign,
  l.utm ->> 'visitor_id'   as visitor_id
from public.leads l
order by l.created_at desc;

-- Lock the views away from the public key as well (belt and braces).
revoke all on public.analytics_daily        from anon;
revoke all on public.analytics_top_pages    from anon;
revoke all on public.analytics_referrers    from anon;
revoke all on public.analytics_sources      from anon;
revoke all on public.analytics_lead_sources from anon;

grant select on public.analytics_daily        to authenticated;
grant select on public.analytics_top_pages    to authenticated;
grant select on public.analytics_referrers    to authenticated;
grant select on public.analytics_sources      to authenticated;
grant select on public.analytics_lead_sources to authenticated;

-- 5. HOUSEKEEPING -------------------------------------------------------------
-- Traffic data grows fast. Run this occasionally (or schedule it with pg_cron)
-- to keep the free tier comfortable. Leads are NEVER touched by this.
create or replace function public.prune_analytics(months integer default 12)
returns integer language plpgsql as $$
declare removed integer;
begin
  delete from public.page_engagement
   where created_at < now() - (months || ' months')::interval;
  delete from public.page_views
   where created_at < now() - (months || ' months')::interval;
  get diagnostics removed = row_count;
  return removed;
end $$;

-- ------------------------------------------------------------
-- HOW TO READ YOUR NUMBERS
--   Supabase dashboard → Table Editor → switch to "Views":
--     analytics_daily         → is traffic growing?
--     analytics_top_pages     → which of the 125 articles actually works
--     analytics_referrers     → Google vs Instagram vs direct
--     analytics_sources       → which campaign paid off
--     analytics_lead_sources  → the article each lead came from
-- ------------------------------------------------------------
